### ISSUE TITLE
Bad Path Explainer

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/segmentation#113]
Given that people have an incredible propensity to generate bad paths, I think it will be worthwhile putting together a function to give interpretable outputs when this happens. 

Adam's idea about a docker-specific warning when people specify a path outside of the mounted volume got me thinking about what such a helper function would look like. 

Currently, when a path doesn't exist, we (usually) at least tell them the reason the function failed was because of a bad path. However, figuring out why the path was bad involves careful staring at the string. 

I think a nice feature would be to add a function that identifies the the most recent common ancestor of the path the user supplied that actually exists. This will help to identify where the typo was. This can be part of a function that does a range of sanity checking for paths, including the docker volume check.

**Comment by ackagel** [comment]
Just added an early version of this to PR #110.  I imagine it could be fleshed out more and added to more instances of general file-loading, which I can do in a separate PR specifically for this issue

**Comment by ngreenwald** [comment]
Here's what the more fleshed out version of this might look like. 

If path is not valid:
    if path does not start with /data:
         Raise an error about non-docker paths
    if path does start with /data:
         loop through parts of the path, and identify the first part that does not exist
         print out that part, as a guide to the user for where the invalid path originated. 


I'm not sure I understand the logic of using pathlib.cwd() in the current implementation. What does that tell us about whether a path is valid or not?

**Comment by ackagel** [comment]
I'm just using `pathlib.Path.cwd()` to get the top-level path to the segmentation folder, since the cwd should never be outside of it.  Currently, when a path doesn't exist, it indexes from its highest folder until it (possibly) reaches 'segmentation', awaiting a mismatch between the path's head and the cwd's head.  If none is found, then the path is inscope, but the file/directory doesn't exist (this could be fleshed out as above regardless).  If a mismatch occurs, there are two cases.  Either 'segmentation' is in the path structure somewhere, meaning this is most likely an absolute path error (path starts out of scope), or 'segmentation' is not in the path structure, meaning the directory/file is totally outside of docker's scope.

That being said, just checking that the path starts with `../data` (or maybe `./data` ?) like your pseudo-code above is probably better, since I think we're encouraging users to put things **only** in that folder, and to only use the codebase from a notebook within `scripts`.  I used the cwd approach for the case where the codebase is used in a notebook or a script with unknown working directory, since the relative path to `data` (or any folder) is ambiguous.

**Comment by ngreenwald** [comment]
Got it. Inside of the docker, the top level path starts where the docker is located:
![image](https://user-images.githubusercontent.com/13770365/86835627-3e665800-c051-11ea-85c5-65e3b0597ca9.png)


I think to make our lives simpler we can enforce all paths starting with /data and get rid of the .../ completely
![image](https://user-images.githubusercontent.com/13770365/86836027-c3ea0800-c051-11ea-8eaa-591b7f0b9b73.png)
