### ISSUE TITLE
Best way to access the code within jupyter

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/segmentation#134]
I believe I've tracked down the problem. Would like to get everyone's input. 

Previously, we weren't installing the code within the docker image, we were just copying it in. This meant that in the old jupyter notebooks, we had to manually add the repo onto the sys.path in order to be able to run the functions, like [this](https://github.com/angelolab/segmentation/blob/be99745ac29e80dcf176bb83438b867d411549cb/scripts/Deepcell_Postprocessing.ipynb)

This looks a bit sloppy, so in a recent PR, I modified the Docker file so that the code is actually installed within the Docker image. This means that we don't have to add the parent directory to the sys.path. 

However, because we made that change in the jupyter notebook, we also needed to update how the repo gets installed within Travis. We currently test the jupyter notebooks by calling nb_convert, which converts them to python and executes them. However, nb_convert uses the system python to run the notebooks, and so without directly installing the repo, the local python kernel doesn't have our package, and hence can't execute the code in the notebooks. 

You can see in [this PR](https://github.com/angelolab/segmentation/pull/116) how I modified the .travis_yml file to install the repo. 

However, this has lead to a new problem. It appears that whenever someone makes a change to the jupyter notebook, coveralls gets confused, and starts including the system installed version of the repo in its coverage report. Since these are not tested, this causes a failure. 

All of these decisions are totally up for debate, let me know what you all think is the best way to handle this

**Comment by ackagel** [comment]
So one way of thinking about what the `sys.path.append('../')` does, is that it changes the `$PATH` environment variable to look for python packages in `segmentation`.  So, instead of doing this in the notebooks, I think we can move this step into the Docker file with a sh/bash line that's something like:

`export PATH=$PATH:/opt/segmentation`

That way, no copying of the repo is needed and it's always clear which file the nb's are importing.  I'm not 100% sure if that will work but it's worth a shot.

**Comment by ackagel** [comment]
I think that line can be added to travis somewhere to avoid copying as well btw

**Comment by ackagel** [comment]
After a bit of research, it looks like jupyter kernels ignore the environment `PATH` variable, and instead use `JUPYTER_PATH`, so substituting that for `PATH` in the above suggestions could work.  It might also be a good idea to add that under the `scripts:` tag in `.travis.yml`

**Comment by ngreenwald** [comment]
Okay, so it seems even with the correct path appended to both jup_path and path, it still doesn't recognize the module

![image](https://user-images.githubusercontent.com/13770365/88248763-20a31080-cc57-11ea-8cea-64fa3e0bab64.png)

It's a bit confusing to me which version of python is actually running the code. Is it is the virtualenv python at the top that's being used to run nb_convert, or the "kernel: python3" within the nb_convert call?
![image](https://user-images.githubusercontent.com/13770365/88248822-5a741700-cc57-11ea-8f2c-569d6e2cb6d8.png)

**Comment by ackagel** [comment]
one more similar thing to try.  Turns out `sys.path` only refers to the `PYTHONPATH` env variable, not the `PATH` env variable.  So try adding segmentation to `PYTHONPATH`.  If this doesn't work, we'll have to do some diagnostics to figure out which python it's using in the notebooks and somehow edit its `PYTHONPATH` var.

**Comment by ackagel** [comment]
exporting `PYTHONPATH` fixed it;  I can add that change to PR #132 or it can be added to the fix coveralls PR #133

**Comment by ngreenwald** [comment]
Can you add it to #133 and make sure everything looks good
