### ISSUE TITLE
Additional testing for channel_spatial_enrichment

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/segmentation#95]
Right now, the testing for channel_spatial_enrichment function is fairly basic, and it's likely that we've missed some potential error modes. We should go back and produce more comprehensive tests, especially for multiple distinct markers with different spatial patterns, to try and identify areas where this slipped through. 

In addition, we should try and find ways to break the test with Erin's data, that doesn't cause our own internal tests to fail.

**Comment by Jaiveers21** [comment]
With the boolean indexing, it assumes that the cell index is the same as the cell label; however issues arise if cell labels are dropped in the expression matrix but kept in the distance matrix. Thus, subsetting be label rather than by boolean seems to be the right approach if the cell labels do not match the indexes in the distance matrix.
